name: Issue Response

on:
  issues:
    types: [opened]

jobs:
  respond:
    runs-on: ubuntu-latest
    steps:
    - name: Respond to issue
      uses: actions/github-script@v3
      with:
        github-token: ${{secrets.PAT_TOKEN}}
        script: |
          const issueComment = `Thank you for opening an issue. We will get back to you soon!`;
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: issueComment
          });
